## Basic Configuration

baseurl = "https://davidweterings.nl"
builddrafts = false
canonifyurls = false
languageCode = "en"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "David Weterings"
title = "Freelance senior software consultant"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "" # Comment out to disable Disqus.
googleAnalytics = ""
enableRobotsTXT = true

## Site Settings
[params]
author = "David Weterings"
intro = ""
description = """
Freelance senior software consultant and polyglot. Focussed on e-commerce, R&D, and cloud-native.

KvK: 71557733 Btw: NL001562249B79
"""
authorimage = "headshot.jpg"
dateformat = "Jan 1, 2025"

## Site Meta Settings
[params.meta]
description = "Freelance senior software developer David Weterings"
keywords = "david weterings,freelance,ZZP,web development,backend development"

## Social Accounts
[params.social]
github = "davidweterings"
linkedin = "davidweterings"
twitter = ""
stackoverflow = ""
email = "david@davidweterings.nl"

## Extras
[params.extra]
copyright = "© 2025. David Weterings. [Some Rights Reserved](https://creativecommons.org/licenses/by/3.0/)."
poweredby = false
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false

## Main Menu
[[menu.main]]
    name = "Resume"
    identifier = "resume"
    weight = 200
    url = "/resume/"

